const express = require("express");
//////////////// admin routes //////////////////////
const adminAttributeRoutes = require("./admin/attribute-routes");
const adminBrandRoutes = require("./admin/brand-routes");
const adminCategoryRoutes = require("./admin/category-routes");
const adminChildCategoryRoutes = require("./admin/child-category-routes");
const adminCouponCodeRoutes = require("./admin/coupon-code-routes");
const adminCurrencyRoutes = require("./admin/currency-routes");
const adminDashboardRoutes = require("./admin/dashboard-routes");
const adminNewsletterRoutes = require("./admin/newsletter-routes");
const adminProductRoutes = require("./admin/product-routes");
const adminRoutes = require("./admin/user-routes");
const adminShopRoutes = require("./admin/shop-routes");
const adminReviewRoutes = require("./admin/review-routes");
const adminPaymentRoutes = require("./admin/payment-routes");
const adminSubCategoryRoutes = require("./admin/sub-category-routes");
const adminSettingsRoutes = require("./admin/setting-routes");
const adminPolicyRoutes = require("./admin/policy-routes");
const adminOrderRoutes = require("./admin/order-routes");
const adminServiceRoutes = require("./admin/service-routes");
//////////////// user routes ///////////////////////
const userAttributeRoutes = require("./user/attribute-routes");
const authRoutes = require("./user/auth-routes");
const adhyatmahRoutes = require("./user/adhyatmah-routes");
const bookingRoutes = require("./user/booking-routes");
const bookingPaymentRoutes = require("./user/booking-payment-routes");
const razorpayPaymentRoutes = require("./user/razorpay-payment-routes");
const razorpayRoutes = require("./user/razorpay-routes");
const homeRoutes = require("./user/home-routes");
const unifiedHomeRoutes = require("./user/unified-home-routes");
const userBrandRoutes = require("./user/brand-routes");
const userCategoryRoutes = require("./user/category-routes");
const userChildCategoryRoutes = require("./user/child-category-routes");
const userCouponCodeRoutes = require("./user/coupon-code-routes");
const userCurrencyRoutes = require("./user/currency-routes");
const delete_fileRoutes = require("./user/file-delete-routes");
const userNewsletterRoutes = require("./user/newsletter-routes");
const searchRoutes = require("./user/search-routes");
const payment = require("./user/payment-intents-routes");
const userProductRoutes = require("./user/product-routes");
const userRoutes = require("./user/user-routes");
const wishlistRoutes = require("./user/wishlist-routes");
const userShopRoutes = require("./user/shop-routes");
const userReviewRoutes = require("./user/review-routes");
const userSubCategoryRoutes = require("./user/sub-category-routes");
const userSettingRoutes = require("./user/setting-routes");
const userPolicyRoutes = require("./user/policy-routes");
const userContactRoutes = require("./user/contact-routes");
const userOrderRoutes = require("./user/order-routes");
const shopifyRoutes = require("./user/shopify-routes");

/////////////// vendor routes //////////////////////
const vendorDashboardRoutes = require("./vendor/dashboard-routes");
const vendorProductRoutes = require("./vendor/product-routes");
const vendorServiceRoutes = require("./vendor/service-routes");
const vendorBookingRoutes = require("./vendor/booking-routes");
const vendorShopRoutes = require("./vendor/shop-routes");
const vendorPaymentRoutes = require("./vendor/payment-routes");
const vendorOrderRoutes = require("./vendor/order-routes");
const vendorRevenueRoutes = require("./vendor/revenue-routes");
const CourierRoutes = require("./vendor/courier-routes");
const router = express.Router();

//////////////// admin routes //////////////////////
router.use("/api", adminAttributeRoutes);
router.use("/api", adminBrandRoutes);
router.use("/api", adminCategoryRoutes);
router.use("/api", adminChildCategoryRoutes);
router.use("/api", adminCouponCodeRoutes);
router.use("/api", adminCurrencyRoutes);
router.use("/api", adminDashboardRoutes);
router.use("/api", adminNewsletterRoutes);
router.use("/api", adminProductRoutes);
router.use("/api", adminRoutes);
router.use("/api", adminShopRoutes);
router.use("/api", adminReviewRoutes);
router.use("/api", adminPaymentRoutes);
router.use("/api", adminSubCategoryRoutes);
router.use("/api", adminSettingsRoutes);
router.use("/api", adminOrderRoutes);
router.use("/api", adminPolicyRoutes);
router.use("/api", adminServiceRoutes);
//////////////// user routes ///////////////////////
router.use("/api", userAttributeRoutes);
router.use("/api", authRoutes);
router.use("/api", adhyatmahRoutes);
router.use("/api", bookingRoutes);
router.use("/api", bookingPaymentRoutes);
router.use("/api", razorpayPaymentRoutes);
router.use("/api", razorpayRoutes);

router.use("/api", homeRoutes);
router.use("/api", unifiedHomeRoutes);
router.use("/api", userBrandRoutes);
router.use("/api", userCategoryRoutes);
router.use("/api", userChildCategoryRoutes);
router.use("/api", userCouponCodeRoutes);
router.use("/api", userCurrencyRoutes);
router.use("/api", userNewsletterRoutes);
router.use("/api", delete_fileRoutes);
router.use("/api", searchRoutes);
router.use("/api", payment);
router.use("/api", userProductRoutes);
router.use("/api", userRoutes);
router.use("/api", wishlistRoutes);
router.use("/api", userShopRoutes);
router.use("/api", userReviewRoutes);
router.use("/api", userSubCategoryRoutes);
router.use("/api", userSettingRoutes);
router.use("/api", userOrderRoutes);
router.use("/api", userPolicyRoutes);
router.use("/api", userContactRoutes);
router.use("/", shopifyRoutes);
/////////////// vendor routes //////////////////////
router.use("/api", vendorDashboardRoutes);
router.use("/api", vendorProductRoutes);
router.use("/api", vendorServiceRoutes);
router.use("/api", vendorBookingRoutes);
router.use("/api", vendorShopRoutes);
router.use("/api", vendorPaymentRoutes);
router.use("/api", vendorOrderRoutes);
router.use("/api", vendorRevenueRoutes);
router.use("/api", CourierRoutes);

module.exports = router;
